### ISSUE TITLE
question on cluster in dataset

### ISSUE THREAD

**Issue by geovedi** [jiangfeng1124/acl15-clnndep#1]
Hi,

I'm curious where did you get the cluster values used in dataset. I couldn't find any reference in the paper or the code. Could you explain how I can get or generate those clusters?

Thanks!
Jim

**Comment by jiangfeng1124** [comment]
Hi Jim,

The clusters are generated using the PROJECTED approach as described in Tackstrom et al., (2012) [refer to Section 5.2 in my paper]. Basically, we first induce brown word clusters at English side, and then project them to other languages through bilingual dictionaries correspondingly.

Jiang

**Comment by geovedi** [comment]
ah, my bad. didn't read that section carefully.
